// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrrY5sA9HID0inonpYHtXJFX2hX5d_L7k',
    appId: '1:268753141414:web:b6504ec5951f663eabfe67',
    messagingSenderId: '268753141414',
    projectId: 'chat-app-48aa9',
    authDomain: 'chat-app-48aa9.firebaseapp.com',
    storageBucket: 'chat-app-48aa9.appspot.com',
    measurementId: 'G-8EDGCS92RE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIH1yFnaJxA8r0CGIjLwLKA5ES9XdysPg',
    appId: '1:268753141414:android:a7c125466c8c0c69abfe67',
    messagingSenderId: '268753141414',
    projectId: 'chat-app-48aa9',
    storageBucket: 'chat-app-48aa9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnO8sE-ZWNqkcUGt3HQfaLKfTgXWVOLyY',
    appId: '1:268753141414:ios:5609dff337e9148cabfe67',
    messagingSenderId: '268753141414',
    projectId: 'chat-app-48aa9',
    storageBucket: 'chat-app-48aa9.appspot.com',
    iosClientId: '268753141414-mkfmhk7k3efq4i6gj36n492igm8uqq5s.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
